
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: dates
    description: 'dates'          

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
#          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowfalke_customer_purchases
    description: "A starter dbt model made by fausto alvarez"
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "first assignement"
    columns:
      - name: o_orderdate
        tests:
          - unique
          - not_null   

  - name: incremental_time
    description: 'incremental_time' 

  - name: playing_with_tests 
    description: 'playing_with_tests'  
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null
      - name: C_MKTSEGMENT
        tests:
          - accepted_values:
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']